wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.10
      5: 0.10.31
      8:
      - 5
data_path:
  desc: null
  value: data/
dropout:
  desc: null
  value: 0.25
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0003
mb_size:
  desc: null
  value: 64
model_path:
  desc: null
  value: models/model.pth
