wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 3
      4: 3.8.10
      5: 0.10.31
      8:
      - 5
channels:
  desc: null
  value: 1
classes:
  desc: null
  value: 10
data_path:
  desc: null
  value: data/
dropout:
  desc: null
  value: 0.25
epochs:
  desc: null
  value: 2
height:
  desc: null
  value: 28
lr:
  desc: null
  value: 0.0003
mb_size:
  desc: null
  value: 64
model_path:
  desc: null
  value: models/model.pth
width:
  desc: null
  value: 28
